# Server Configuration
server.port=8080
server.servlet.context-path=/acme-envio-pedidos

# External API Configuration
external.api.url=https://run.mocky.io/v3/19217075-6d4e-4818-98bc-416d1feb7b84

# Logging Configuration
logging.level.com.acme.enviopedidos=DEBUG
logging.level.org.springframework.web=DEBUG

# Jackson Configuration
spring.jackson.serialization.indent-output=true
